@Library(value='kids-first/aws-infra-jenkins-shared-libraries', changelog=false) _
ecs_service_type_1_standard {
    projectName             = "kf-api-portal-reports"
    orgFullName             = "kids-first"
    account                 = "kf-strides"
    environments            = "qa,prd"
    docker_image_type       = "alpine"
    create_default_iam_role = "1"
    entrypoint_command      = "node ./dist/index.js"
    quick_deploy            = "true"
    container_port          = "80"
    health_check_path       = "/status"
    external_config_repo    = "false"
    dependencies            = "ecr"
    internal_app            = "false"
    vcpu_container          = "2048"
    memory_container        = "4096"
    vcpu_task               = "2048"
    memory_task             = "4096"
    additional_ssl_cert_domain_name = "*.kidsfirstdrc.org"
    publish_to_public_repo = "true"
}
